# See CKAN docs on installation from Docker Compose on usage
FROM python:3.8.7-buster
MAINTAINER Open Knowledge

# Install required system packages
RUN apt-get -q -y update \
    && DEBIAN_FRONTEND=noninteractive apt-get -q -y upgrade \
    && apt-get -q -y install \
	build-essential \
        vim \
        wget \
	locales \
	locales-all \
    && apt-get -q clean \
    && rm -rf /var/lib/apt/lists/*

# Define environment variables
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Build-time variables specified by docker-compose.yml / .env


# Setup virtual environment for datapusher
RUN mkdir -p /usr/lib/ckan/datapusher && \
    python3 -m venv /usr/lib/ckan/datapusher && \
    mkdir -p /usr/lib/ckan/datapusher/src && \
   ln -s /usr/lib/ckan/datapusher/bin/pip /usr/local/bin/datapusher-pip && \
   ln -s /usr/lib/ckan/datapusher/bin/uwsgi /usr/local/bin/datapusher-uwsgi

# Setup datapusher
ADD datapusher /usr/lib/ckan/datapusher/src/datapusher
RUN datapusher-pip install -U pip && \
    datapusher-pip install -r /usr/lib/ckan/datapusher/src/datapusher/requirements.txt && \
    datapusher-pip install /usr/lib/ckan/datapusher/src/datapusher && \
    datapusher-pip install uwsgi

CMD ["datapusher-uwsgi","-i","/usr/lib/ckan/datapusher/src/datapusher/deployment/datapusher-uwsgi.ini"]
#CMD ["ping", "horton-server"]
